### ISSUE TITLE
Duplicate test IDs in 1.1.0

### ISSUE THREAD

**Issue by nkraemer-sysdig** [aquasecurity/linux-bench#45]
There are two tests with the ID `4.1.9.a` and `4.1.9.b` in `cfg/1.1.0/definitions.yaml`. These tests are distinct, and should have unique IDs.

**Comment by yoavrotems** [comment]
Hello, first of all thanks for your feedback.
Those tests are derivative from the same test in the CIS_Distribution_Independent_Linux_Benchmark book , just separated into two checks from logistic reasons.
Furthermore on the relations between them - 
The first one checks the auditd rules file 

> grep session /etc/audit/audit.rules

While the second one checks the live system active rules 
> auditctl -l | grep session 

Because rules in .rule file and running rules are not necessarily the same.
 (There could be changes with auditctl which will not apply to the .rule file but do apply to the running rule set)
